begin;
do $$
declare org uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); t uuid:=gen_random_uuid(); other_t uuid:=gen_random_uuid(); s uuid:=gen_random_uuid(); other_s uuid:=gen_random_uuid();
 am bigint; tm bigint; otm bigint; sm bigint; osm bigint; g bigint; result jsonb; blocked boolean; actor uuid;
begin
 insert into public.organizations(id,slug,name,created_at) values(org,'test-'||org::text,'Profile regression test',now()-interval '3 months');
 foreach actor in array array[a,t,other_t,s,other_s] loop
   insert into auth.users(id,email,raw_user_meta_data) values(actor,actor::text||'@example.invalid','{"full_name":"Profile Test","registration_role":"student"}');
 end loop;
 insert into public.memberships(organization_id,profile_id,role) values(org,a,'admin') returning id into am;
 insert into public.memberships(organization_id,profile_id,role) values(org,t,'teacher') returning id into tm;
 insert into public.memberships(organization_id,profile_id,role) values(org,other_t,'teacher') returning id into otm;
 insert into public.memberships(organization_id,profile_id,role) values(org,s,'student') returning id into sm;
 insert into public.memberships(organization_id,profile_id,role) values(org,other_s,'student') returning id into osm;
 insert into private.metric_baseline(organization_id,started_at) values(org,now()-interval '2 months');
 update private.metric_history set captured_at=now()-interval '45 days' where organization_id=org;
 insert into public.groups(organization_id,name,course,teacher_membership_id) values(org,'Test group','Test course',tm) returning id into g;
 insert into public.enrollments(organization_id,group_id,student_membership_id) values(org,g,sm);
 perform set_config('request.jwt.claim.sub',s::text,true);
 blocked:=false; begin perform public.save_profile(sm,'{"first_name":"Student","last_name":"Own","age":19}'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'student edited own personal fields'; end if;
 blocked:=false; begin perform public.save_profile(sm,'{}',null,'admin'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'student escalated role'; end if;
 blocked:=false; begin perform public.save_profile(osm,'{"first_name":"Unauthorized"}'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'student edited other profile'; end if;
 blocked:=false; begin perform public.save_profile(sm,'{}','graduated'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'student changed outcome'; end if;
 blocked:=false; begin perform public.dashboard_metrics(org); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'student accessed org metrics'; end if;
 if not private.can_edit_profile(s) or private.can_edit_profile(t) then raise exception 'avatar student access incorrect'; end if;
 perform set_config('request.jwt.claim.sub',t::text,true);
 perform public.save_profile(sm,'{}','graduated');
 if (select study_status from public.memberships where id=sm)<>'graduated' or (select graduated_at from public.memberships where id=sm) is null then raise exception 'teacher grading failed'; end if;
 blocked:=false; begin perform public.save_profile(sm,'{"first_name":"Unauthorized"}'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'teacher edited student personal fields'; end if;
 blocked:=false; begin perform public.save_profile(osm,'{}','graduated'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'teacher graded unrelated student'; end if;
 if private.can_edit_profile(s) then raise exception 'teacher can alter student avatar'; end if;
 perform set_config('request.jwt.claim.sub',other_t::text,true);
 blocked:=false; begin perform public.save_profile(sm,'{}','studying'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'unassigned teacher changed outcome'; end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform public.save_profile(osm,'{"first_name":"Admin","last_name":"Edited","phone":"123"}','unsuccessful');
 if (select full_name from public.profiles where id=other_s)<>'Admin Edited' then raise exception 'admin edit failed'; end if;
 if not private.can_edit_profile(other_s) then raise exception 'admin avatar access incorrect'; end if;
 result:=public.dashboard_metrics(org);
 if (result#>>'{current,employees}')::int<>3 or (result#>>'{current,students}')::int<>2 or
    (result#>>'{current,graduates}')::int<>2 or (result#>>'{current,success_rate}')::numeric<>50 then raise exception 'current metrics wrong: %',result; end if;
 if (result#>>'{previous,graduates}')::int<>0 or (result#>>'{previous,students}')::int<>2 then raise exception 'history wrong: %',result; end if;
 perform public.save_profile(sm,'{}','studying');
 if (select graduated_at from public.memberships where id=sm) is not null then raise exception 'graduation date not cleared'; end if;
 perform public.save_profile(osm,'{}',null,'teacher');
 result:=public.dashboard_metrics(org);
 if (result#>>'{current,employees}')::int<>4 or (result#>>'{current,students}')::int<>1 or (result#>>'{current,graduates}')::int<>0 then raise exception 'role metric change failed: %',result; end if;
 update private.metric_baseline set started_at=now() where organization_id=org;
 result:=public.dashboard_metrics(org);
 if result->'previous'<>'null'::jsonb then raise exception 'missing history invented'; end if;
 update public.organizations set created_at=now() where id=org;
 result:=public.dashboard_metrics(org);
 if (result#>>'{previous,students}')::int<>0 then raise exception 'new organization baseline wrong'; end if;
 blocked:=false; begin perform public.save_profile(am,'{}',null,'student'); exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'last admin demoted'; end if;
end $$;
rollback;
select 'Profile permissions, avatar authorization, outcomes and monthly history checks passed; all fixtures rolled back.' as result;
